"use client";

import { Save, Settings2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import { getConfiguration, listPracticeHistory, saveConfiguration, type ConfigurationView } from "@/lib/exam-mem-product";

const BACKENDS = ["none", "native", "append_only", "vector", "lifecycle"];

export default function ExamMemConfiguration() {
  const { t } = useTranslation();
  const [view, setView] = useState<ConfigurationView | null>(null);
  const [backend, setBackend] = useState("lifecycle");
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { void listPracticeHistory().then((history) => getConfiguration(history[0]?.practice_session_id)).then((value) => { setView(value); setBackend(value.saved.settings.memory_backend); }).catch((cause) => setError(cause instanceof Error ? cause.message : t("Configuration failed to load."))); }, [t]);
  const save = async () => { if (!view) return; setSaving(true); setError(null); try { const next = await saveConfiguration({ ...view.saved.settings, memory_backend: backend }); setView(next); } catch (cause) { setError(cause instanceof Error ? cause.message : t("Configuration save failed.")); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6 lg:px-10"><header className="flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--primary)]/10 text-[var(--primary)]"><Settings2 className="h-5 w-5" /></span><div><h1 className="font-serif text-2xl font-semibold">{t("Configuration")}</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">{t("Saved applies after restart to new exams; Effective is this process; Pinned remains fixed per exam.")}</p></div></header>{error ? <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-600">{error}</p> : null}{view ? <><section className="grid gap-4 md:grid-cols-3"><ConfigCard title={t("Saved")} state={view.saved} /><ConfigCard title={t("Effective")} state={view.effective} />{view.pinned ? <PinnedCard state={view.pinned} /> : <article className="rounded-xl border border-dashed border-[var(--border)] p-5 text-sm text-[var(--muted-foreground)]">{t("Pinned: no existing exam")}</article>}</section><section className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="font-semibold">{t("Backend for new exams")}</h2><select value={backend} onChange={(event) => setBackend(event.target.value)} className="mt-3 w-full rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-sm md:max-w-sm">{BACKENDS.map((item) => <option key={item} value={item}>{item}</option>)}</select><p className="mt-3 text-xs text-[var(--muted-foreground)]">{t("Side effects are derived from Backend and cannot be toggled independently.")}</p><button type="button" disabled={saving} onClick={() => void save()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm text-[var(--primary-foreground)] disabled:opacity-50"><Save className="h-4 w-4" />{t("Save for controlled restart")}</button>{view.restart_required ? <p className="mt-3 text-sm text-amber-600">{t("Restart required. Effective configuration has not changed.")}</p> : null}</section></> : null}</div>;
}

function ConfigCard({ title, state }: { title: string; state: ConfigurationView["saved"] }) { const { t } = useTranslation(); return <article className="min-w-0 rounded-xl border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="font-semibold">{title}</h2><p className="mt-2 break-all font-mono text-xs text-[var(--muted-foreground)]">{state.revision}</p><p className="mt-3 text-sm">{t("Backend")}: <strong>{state.settings.memory_backend}</strong></p><div className="mt-3 flex flex-wrap gap-2">{state.side_effects.map((item) => <span key={item} className="rounded-full bg-[var(--muted)] px-2 py-1 text-xs">{item}</span>)}</div></article>; }
function PinnedCard({ state }: { state: NonNullable<ConfigurationView["pinned"]> }) { const { t } = useTranslation(); return <article className="min-w-0 rounded-xl border border-[var(--primary)]/30 bg-[var(--card)] p-5"><h2 className="font-semibold">{t("Pinned current exam")}</h2><p className="mt-2 break-all font-mono text-xs text-[var(--muted-foreground)]">{state.config_revision}</p><p className="mt-3 text-sm">{t("Backend")}: <strong>{state.backend_mode}</strong></p><div className="mt-3 flex flex-wrap gap-2">{state.side_effects.map((item) => <span key={item} className="rounded-full bg-[var(--muted)] px-2 py-1 text-xs">{item}</span>)}</div></article>; }
